### ISSUE TITLE
npm ERR! code EACCES on `npm install -g json`

### ISSUE THREAD

**Issue by brouwer** [fractal-code/meteor-azure#13]
Has been working for a while now, but recently started failing. Please note the invalid startup command has never been an issue, when the script was still working it would also warn about this. 

- Script version: 1.1.2

- Deployment log
```
Command: bash .config/azure/deploy.sh
Invalid start-up command "meteor --settings settings-development.json" in package.json. Please use the format "node <script relative path>".
Looking for app.js/server.js under site root.
Missing server.js/app.js files, web.config is not generated
The package.json file does not specify node.js engine version constraints.
The node.js application will run with the default node.js version 4.6.2.
Selected npm version null
One or more of the selected node/npm paths do not exist.
meteor-azure: Setting NPM version
npm http GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
D:\local\AppData\npm\npm -> D:\local\AppData\npm\node_modules\npm\bin\npm-cli.js
npm@3.10.9 D:\local\AppData\npm\node_modules\npm
3.10.9
meteor-azure: Building app
meteor-azure: Deploying bundle
meteor-azure: Installing JSON tool
D:\Program Files (x86)\nodejs\0.10.28
npm WARN checkPermissions Missing write access to D:\Program Files (x86)\nodejs\0.10.28
`-- json@9.0.4
npm ERR! Windows_NT 6.2.9200

npm ERR! argv "D:\\Program Files (x86)\\nodejs\\0.10.28\\node.exe" "C:\\DWASFiles\\Sites\\#1devmyapp\\AppData\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "json"
npm ERR! node v0.10.28
npm ERR! npm  v3.10.9
meteor-azure: Preparing package.json
npm ERR! path D:\Program Files (x86)\nodejs\0.10.28
npm ERR! code EACCES

npm ERR! Error: EACCES, access 'D:\Program Files (x86)\nodejs\0.10.28'
npm ERR!     at module.exports (C:\DWASFiles\Sites\#1devmyapp\AppData\npm\node_modules\npm\lib\install\access-error.js:4:18)
npm ERR!     at C:\DWASFiles\Sites\#1devmyapp\AppData\npm\node_modules\npm\lib\install\writable.js:30:25
npm ERR!     at C:\DWASFiles\Sites\#1devmyapp\AppData\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:241:16
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR!  { [Error: EACCES, access 'D:\Program Files (x86)\nodejs\0.10.28']
npm ERR!   code: 'EACCES',
npm ERR!   path: 'D:\\Program Files (x86)\\nodejs\\0.10.28' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

.config/azure/deploy.sh: line 153: json: command not found
meteor-azure: Installing NPM packages
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\0.10.28\\node.exe" "C:\\DWASFiles\\Sites\\#1devmyapp\\AppData\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v0.10.28
npm ERR! npm  v3.10.9
npm ERR! file D:\home\site\wwwroot\programs\server\package.json
npm ERR! code EJSONPARSE
An error has occurred during web site deployment.

npm failed
npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: D:\home\site\wwwroot\programs\server\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

Invalid start-up command "meteor --settings settings-development.json" in package.json. Please use the format "node <script relative path>".\r\nMissing server.js/app.js files, web.config is not generated\r\nnpm http GET https://registry.npmjs.org/npm\r\nnpm http 304 https://registry.npmjs.org/npm\r\nnpm WARN checkPermissions Missing write access to D:\Program Files (x86)\nodejs\0.10.28\r\nnpm ERR! Windows_NT 6.2.9200\r\nnpm ERR! argv "D:\\Program Files (x86)\\nodejs\\0.10.28\\node.exe" "C:\\DWASFiles\\Sites\\#1devmyapp\\AppData\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "json"\r\nnpm ERR! node v0.10.28\r\nnpm ERR! npm  v3.10.9\r\nnpm ERR! path D:\Program Files (x86)\nodejs\0.10.28\r\nnpm ERR! code EACCES\r\n\r\nnpm ERR! Error: EACCES, access 'D:\Program Files (x86)\nodejs\0.10.28'\r\nnpm ERR!     at module.exports (C:\DWASFiles\Sites\#1devmyapp\AppData\npm\node_modules\npm\lib\install\access-error.js:4:18)\r\nnpm ERR!     at C:\DWASFiles\Sites\#1devmyapp\AppData\npm\node_modules\npm\lib\install\writable.js:30:25\r\nnpm ERR!     at C:\DWASFiles\Sites\#1devmyapp\AppData\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:241:16\r\nnpm ERR!     at Object.oncomplete (fs.js:107:15)\r\nnpm ERR!  { [Error: EACCES, access 'D:\Program Files (x86)\nodejs\0.10.28']\r\nnpm ERR!   code: 'EACCES',\r\nnpm ERR!   path: 'D:\\Program Files (x86)\\nodejs\\0.10.28' }\r\nnpm ERR! \r\nnpm ERR! Please try running this command again as root/Administrator.\r\n\r\n.config/azure/deploy.sh: line 153: json: command not found\r\nnpm ERR! Windows_NT 6.2.9200\r\nnpm ERR! argv "D:\\Program Files (x86)\\nodejs\\0.10.28\\node.exe" "C:\\DWASFiles\\Sites\\#1devmyapp\\AppData\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"\r\nnpm ERR! node v0.10.28\r\nnpm ERR! npm  v3.10.9\r\nnpm ERR! file D:\home\site\wwwroot\programs\server\package.json\r\nnpm ERR! code EJSONPARSE\r\n\r\nnpm ERR! Failed to parse json\r\nnpm ERR! No data, empty input at 1:1\r\nnpm ERR! \r\nnpm ERR! ^\r\nnpm ERR! File: D:\home\site\wwwroot\programs\server\package.json\r\nnpm ERR! Failed to parse package.json data.\r\nnpm ERR! package.json must be actual JSON, not just JavaScript.\r\nnpm ERR! \r\nnpm ERR! This is not a bug in npm.\r\nnpm ERR! Tell the package author to fix their package.json file. JSON.parse\r\nD:\Program Files (x86)\SiteExtensions\Kudu\59.51202.2583\bin\Scripts\starter.cmd bash .config/azure/deploy.sh
```

**Comment by ramijarrar** [comment]
We actually ran into this recently ourselves - the issue is that Azure only supports a limited selection of Node versions out-of-the-box and v4.6.2 is not currently available.

We are aware that this is the recommended release as of Meteor 1.4.2.2 and are working on a custom solution to address this (hoping to get that out later tonight/tomorrow morning). 

In the meantime, you can still deploy with Node 4.6.1

**Comment by ramijarrar** [comment]
Just released v1.2.0 which implements custom node version management.

Let me know if you have any issues using that.

**Comment by brouwer** [comment]
No issues with using 4.6.1, wouldn't have guessed that was the problem, thanks

**Comment by ramijarrar** [comment]
No problem, keep in mind that you can use 4.6.2 if you upgrade to v1.2.0 of the script (which is not limited by Azure's preinstalled Node selection)
