### ISSUE TITLE
Getting [Error: ENOTEMPTY: directory not empty, rmdir 'D:\local\Temp\mt-irythc']

### ISSUE THREAD

**Issue by wilcraig** [fractal-code/meteor-azure#19]
Hey guys, getting error that a directory isn't empty. Here's the log:

```sh
Command: bash .config/azure/deploy.sh
meteor-azure: Setting Node version
Version 4.7.3 is already installed.
meteor-azure: Now using Node v4.7.3 (32-bit)
meteor-azure: Setting NPM version
meteor-azure: Now using NPM v4.1.2
meteor-azure: Installing NPM dependencies
meteor-azure: Building app
{ [Error: ENOTEMPTY: directory not empty, rmdir 'D:\local\Temp\mt-irythc']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'D:\\local\\Temp\\mt-irythc' }
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EOF
    at exports._errnoException (util.js:907:11)
    at WriteWrap.afterWrite (net.js:785:14)
meteor-azure: ERROR! Could not generate Meteor bundle
events.js:141\r\n      throw er; // Unhandled 'error' event\r\n      ^\r\n\r\nError: write EOF\r\n    at exports._errnoException (util.js:907:11)\r\n    at WriteWrap.afterWrite (net.js:785:14)\r\nD:\Program Files (x86)\SiteExtensions\Kudu\59.60207.2684\bin\Scripts\starter.cmd bash .config/azure/deploy.sh
```

**Comment by ramijarrar** [comment]
Can you confirm which version of the script you're using?

**Comment by ramijarrar** [comment]
Closing due to no response. 

Please reopen if this is still an issue.
