### ISSUE TITLE
Error: Deploying bundle tarball 

### ISSUE THREAD

**Issue by XAMelleOH** [fractal-code/meteor-azure#33]
One day back it worked fine. Nothing changed on my side, can't understand why it fails

- Operating system: Mac OS

- Meteor version: 1.5

- Package version (run `meteor-azure -v`) 2.0.4

- Command output with debug mode enabled
<img width="953" alt="image" src="https://user-images.githubusercontent.com/283614/27309879-2d2c1a30-555f-11e7-8fea-d9bb2d347982.png">

- Log file content:
```0 info it worked if it ends with ok
1 verbose cli [ '/Users/andriy/local/bin/node',
1 verbose cli   '/Users/andriy/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy-test' ]
2 info using npm@5.0.3
3 info using node@v7.4.0
4 verbose run-script [ 'predeploy-test', 'deploy-test', 'postdeploy-test' ]
5 info lifecycle hib-meteor@~predeploy-test: hib-meteor@
6 silly lifecycle hib-meteor@~predeploy-test: no script for predeploy-test, continuing
7 info lifecycle hib-meteor@~deploy-test: hib-meteor@
8 verbose lifecycle hib-meteor@~deploy-test: unsafe-perm in lifecycle true
9 verbose lifecycle hib-meteor@~deploy-test: PATH: /Users/andriy/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/andriy/Work/GetBetter/Sonova/HIB/hib/node_modules/.bin:/usr/local/Cellar/:/Users/andriy/Work/tests/apache-maven-3.5.0/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/Users/andriy/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
10 verbose lifecycle hib-meteor@~deploy-test: CWD: /Users/andriy/Work/HIB/hib
11 silly lifecycle hib-meteor@~deploy-test: Args: [ '-c',
11 silly lifecycle   'git checkout dev && ./node_modules/.bin/meteor-azure --settings environments/env.test.json --web-config web.config -d' ]
12 silly lifecycle hib-meteor@~deploy-test: Returned: code: 1  signal: null
13 info lifecycle hib-meteor@~deploy-test: Failed to exec deploy-test script
14 verbose stack Error: hib-meteor@ deploy-test: `git checkout dev && ./node_modules/.bin/meteor-azure --settings environments/env.test.json --web-config web.config -d`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/andriy/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/andriy/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid hib-meteor@
16 verbose cwd /Users/andriy/Work/GetBetter/Sonova/HIB/hib
17 verbose Darwin 16.6.0
18 verbose argv "/Users/andriy/local/bin/node" "/Users/andriy/local/bin/npm" "run" "deploy-test"
19 verbose node v7.4.0
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error hib-meteor@ deploy-test: `git checkout dev && ./node_modules/.bin/meteor-azure --settings environments/env.test.json --web-config web.config -d`
23 error Exit status 1
24 error Failed at the hib-meteor@ deploy-test script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by ramijarrar** [comment]
Your deployment credentials are invalid. An easy way this can happen, is if you change them in another project (they are applicable to any app in your account).

Can you double-check in the Azure portal and see if the issue persists?

**Comment by XAMelleOH** [comment]
@ramijarrar You are 100% right, I've created another project and regenerated credentials by mistake. Sorry!
