### ISSUE TITLE
Error: Cannot find module 'meteor-deque'

### ISSUE THREAD

**Issue by ramijarrar** [fractal-code/meteor-azure#60]
Originally reported by @WayneUong  in https://github.com/fractal-code/meteor-azure/issues/59#issuecomment-409022728

> So I deployed a bare app with `meteor create` and the error still appear once before the app is started:

```bash
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module 'D:\home\site\wwwroot\programs\server\npm\node_modules\meteo \meteor\node_modules\meteor-deque'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.require (D:\home\site\wwwroot\programs\server\boot.js:284:20)
    at packages\meteor.js:854:32
    at packages\meteor.js:1025:4
    at packages\meteor.js:1578:3
    at D:\home\site\wwwroot\programs\server\boot.js:411:36
    at Array.forEach (<anonymous>)
```

**Comment by ramijarrar** [comment]
I'll see if I can reproduce with a bare meteor create (based on meteor/meteor#8556 it seems like it might be an issue with the local environment)

**Comment by WayneUong** [comment]
Because the app would eventually startups, I think it might be a race condition where azure is trying to start the app when not all data is initialized.

**Comment by WayneUong** [comment]
I also got various other missing module errors as well:

```
## There is an issue with `node-fibers` ##
`D:\home\site\wwwroot\programs\server\node_modules\fibers\bin\win32-x64-57\fibers.node` is missing.

Try running this to fix the issue: D:\home\meteor-azure\nvm\v8.11.3\node.exe D:\home\site\wwwroot\programs\server\node_modules\fibers/build
Application has thrown an uncaught exception and is terminated:
Error: Missing binary. See message above.
    at Object.<anonymous> (D:\home\site\wwwroot\programs\server\node_modules\fibers\fibers.js:20:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\home\site\wwwroot\programs\server\boot.js:1:75)
    at Module._compile (module.js:652:30)
```
```
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module 'double-ended-queue'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\home\site\wwwroot\programs\server\npm\node_modules\meteor\meteor\node_modules\meteor-deque\index.js:1:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

**Comment by ramijarrar** [comment]
I'm going to investigate this later tonight - for now you should be able to workaround the issue by using another deployment slot and waiting for the app to start correctly before swapping.

**Comment by ramijarrar** [comment]
I've tried deploying an app with ``meteor create --bare`` on 64-bit but am not able to reproduce the errors.

Can you confirm your package.json looks like:

```json
{
  "name": "meteor-azure-test",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "deploy": "meteor-azure --architecture 64 --settings settings.json",
    "test": "meteor test --once --driver-package meteortesting:mocha",
    "test-app": "TEST_WATCH=1 meteor test --full-app --driver-package meteortesting:mocha",
    "visualize": "meteor --production --extra-packages bundle-visualizer"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0-beta.51",
    "meteor-node-stubs": "^0.4.1"
  },
  "meteor": {
    "mainModule": {
      "client": "client/main.js",
      "server": "server/main.js"
    },
    "testModule": "tests/main.js"
  },
  "devDependencies": {
    "meteor-azure": "^2.1.0-rc.7"
  }
}
```

**Comment by ramijarrar** [comment]
@WayneUong Not sure if this is still a problem for you but have seen this issue pop-up with one of our own apps that mistakenly had the "meteor-azure" package as a regular dependency (rather than dev-only). Am closing for now due to inactivity - please re-open if still affecting you.
