### ISSUE TITLE
Getting error after updating Meteor to version 2.5 

### ISSUE THREAD

**Issue by 55** [fractal-code/meteor-azure#78]
Before: smooth deployment process with Meteor 1.12.1  

Now getting this error: 
```
Application has thrown an uncaught exception and is terminated:
Error: \\?\C:\home\site\wwwroot\programs\server\npm\node_modules\meteor\accounts-password\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node is not a valid Win32 application.

\\?\C:\home\site\wwwroot\programs\server\npm\node_modules\meteor\accounts-password\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Module.Mp.load (C:\home\site\wwwroot\programs\server\runtime.js:46:33)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\home\site\wwwroot\programs\server\npm\node_modules\meteor\accounts-password\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.Mp._compile (C:\home\site\wwwroot\programs\server\runtime.js:99:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Module.Mp.load (C:\home\site\wwwroot\programs\server\runtime.js:46:33)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at npmRequire (C:\home\site\wwwroot\programs\server\npm-require.js:133:12)
```

**Comment by 55** [comment]
@ramijarrar any ideas?

**Comment by ramijarrar** [comment]
Can you confirm all the dependencies in your `package.json`, as well as the output of `meteor list`?

**Comment by 55** [comment]
```
  "dependencies": {
    "@auth0/auth0-spa-js": "^1.13.6",
    "@babel/runtime": "^7.13.9",
    "@fortawesome/fontawesome-free": "^5.15.2",
    "async": "^3.2.0",
    "bcrypt": "^5.0.1",
    "body-parser": "^1.19.0",
    "bootstrap": "^4.6.0",
    "bootstrap-datepicker": "^1.9.0",
    "chart.js": "^2.9.4",
    "cron": "^1.8.2",
    "datatables.net-bs4": "^1.10.23",
    "datatables.net-responsive-bs4": "^2.2.7",
    "jquery": "^3.5.1",
    "meteor-node-stubs": "^1.0.1",
    "popper.js": "^1.16.1",
    "underscore": "^1.12.0",
    "xlsx": "^0.16.9"
  }
```

```
accounts-base                    1.7.1* A user account system
accounts-password                1.6.3* Password support for accounts
alanning:roles                   3.2.3* Authorization package for Meteor
blaze-html-templates             1.1.2* Compile HTML templates into reactive UI with Meteor Blaze
ecmascript                       0.14.4* Compiler plugin that supports ES2015+ in all .js files
email                            2.0.0* Send email messages
es5-shim                         4.8.0  Shims and polyfills to improve ECMAScript 5 support
gaetanrouzies:bootstrap-4-modal  0.0.6  Simply open and hide bootstrap 4 modals in Meteor.
http                             1.4.2* Make HTTP calls to remote servers
jquery                           3.0.0  Manipulate the DOM using CSS selectors
kadira:blaze-layout              2.0.1* Layout Manager for Blaze (works well with FlowRouter)
less                             2.8.0* Leaner CSS language
meteor-base                      1.4.0* Packages that every Meteor app needs
mobile-experience                1.1.0  Packages for a great mobile user experience
mongo                            1.10.1* Adaptor for using MongoDB and Minimongo over DDP
optune:auth0-oauth               1.0.0+ OAuth handler for Auth0 with Meteor Accounts including support for inline lock widget
ostrio:flow-router-extra         3.7.5  Carefully extended flow-router with waitOn and template context
reactive-var                     1.0.11  Reactive variable
sacha:spin                       2.3.1  Simple spinner package for Meteor
session                          1.2.0  Session variable
shell-server                     0.5.0  Server-side component of the `meteor shell` command.
skinnygeek1010:validate-form     1.0.1  An extendable form validator
standard-minifier-css            1.7.1* Standard css minifier used with Meteor apps by default.
standard-minifier-js             2.6.0* Standard javascript minifiers used with Meteor apps by default.
themeteorchef:bert               2.2.1* A client side, multi-style alerts system for Meteor.
tracker                          1.2.0  Dependency tracker to allow reactive callbacks
underscore                       1.0.10  Collection of small helpers: _.map, _.each, ...
universe:i18n                    1.31.0* Lightweight i18n, YAML & JSON translation files, React component, incremental & remote loading
universe:i18n-blaze              1.5.1  Gives a universe translation helper in blaze
```

**Comment by ramijarrar** [comment]
You are on an outdated version of `accounts-password` that doesn't use the newer npm bcrypt you have installed.

Upgrading this to the latest version 2.2.0 should solve this.

Just edit your `.meteor/packages` file (make sure to run Meteor at least once before re-deploying):

```
accounts-base@2.2.0
accounts-password@2.2.0
```

You should also consider running `meteor update --all-packages` as you have many very old versions of core packages as "ecmascript", "standard-minifier-js", "meteor-base", etc.

**Comment by 55** [comment]
@ramijarrar my apologies, I was on a wrong branch :(

here is the correct list

```
accounts-base                    2.2.0  A user account system
accounts-password                2.2.0  Password support for accounts
alanning:roles                   3.4.0  Authorization package for Meteor
blaze-html-templates             1.2.1  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript                       0.16.0  Compiler plugin that supports ES2015+ in all .js files
email                            2.2.0  Send email messages
es5-shim                         4.8.0  Shims and polyfills to improve ECMAScript 5 support
gaetanrouzies:bootstrap-4-modal  0.0.6  Simply open and hide bootstrap 4 modals in Meteor.
http                             1.4.4* Make HTTP calls to remote servers
jquery                           3.0.0  Manipulate the DOM using CSS selectors
kadira:blaze-layout              2.0.1* Layout Manager for Blaze (works well with FlowRouter)
less                             2.8.0* Leaner CSS language
meteor-base                      1.5.1  Packages that every Meteor app needs
mobile-experience                1.1.0  Packages for a great mobile user experience
mongo                            1.13.0  Adaptor for using MongoDB and Minimongo over DDP
optune:auth0-oauth               1.0.0+ OAuth handler for Auth0 with Meteor Accounts including support for inline lock widget
ostrio:flow-router-extra         3.7.5  Carefully extended flow-router with waitOn and template context
reactive-var                     1.0.11  Reactive variable
sacha:spin                       2.3.1  Simple spinner package for Meteor
session                          1.2.0  Session variable
shell-server                     0.5.0  Server-side component of the `meteor shell` command.
skinnygeek1010:validate-form     1.0.1  An extendable form validator
standard-minifier-css            1.7.4  Standard css minifier used with Meteor apps by default.
standard-minifier-js             2.7.2* Standard javascript minifiers used with Meteor apps by default.
themeteorchef:bert               2.2.1* A client side, multi-style alerts system for Meteor.
tracker                          1.2.0  Dependency tracker to allow reactive callbacks
underscore                       1.0.10  Collection of small helpers: _.map, _.each, ...
universe:i18n                    1.31.0* Lightweight i18n, YAML & JSON translation files, React component, incremental & remote loading
universe:i18n-blaze              1.5.1  Gives a universe translation helper in blaze
```

**Comment by ramijarrar** [comment]
Are the NPM dependencies correct?

**Comment by 55** [comment]
Here is the update list:

```
"dependencies": {
    "@auth0/auth0-spa-js": "^1.19.2",
    "@babel/runtime": "^7.16.3",
    "@fortawesome/fontawesome-free": "^5.15.4",
    "async": "^3.2.2",
    "bcrypt": "^5.0.1",
    "body-parser": "^1.19.0",
    "bootstrap": "^4.6.1",
    "bootstrap-datepicker": "^1.9.0",
    "chart.js": "^2.9.4",
    "cron": "^1.8.2",
    "datatables.net-bs4": "^1.11.3",
    "datatables.net-responsive-bs4": "^2.2.9",
    "jquery": "^3.5.1",
    "meteor-node-stubs": "^1.1.0",
    "popper.js": "^1.16.1",
    "underscore": "^1.13.1",
    "xlsx": "^0.16.9"
  }
```

**Comment by ramijarrar** [comment]
Can you try redeploying to a new app or [staging slot](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots) and let me know if the error persists?

**Comment by 55** [comment]
Hmm, and now it fails...

```
debug:   npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
debug:   C:\home\meteor-azure\nvm\v14.18.1\node-pre-gyp -> C:\home\meteor-azure\nvm\v14.18.1\node_modules\node-pre-gyp\bin\node-pre-gyp
debug:   + node-pre-gyp@0.14.0
debug:   updated 1 package in 5.204s
debug:   meteor-azure: Unpacking bundle
debug:   meteor-azure: Using default web config
debug:   meteor-azure: Setting Node runtime
debug:   meteor-azure: Enabling IISNode logging
debug:   meteor-azure: Installing NPM dependencies
debug:   /tmp/8d9b34023bcfd48/bundle/programs/server /tmp/8d9b34023bcfd48
debug:   npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
debug:    
debug:   > fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install C:\local\Temp\8d9b34023bcfd48\bundle\programs\server\node_modules\fibers
debug:   > node build.js || nodejs build.js
debug:    
debug:    
debug:   C:\local\Temp\8d9b34023bcfd48\bundle\programs\server\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\home\meteor-azure\nvm\v14.18.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\home\meteor-azure\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release ) 
debug:   Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
debug:   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.props(28,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Redirect.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [C:\local\Temp\8d9b34023bcfd48\bundle\programs\server\node_modules\fibers\build\fibers.vcxproj]
debug:   gyp ERR! build error 
debug:   gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
debug:   gyp ERR! stack     at ChildProcess.onExit (C:\home\meteor-azure\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
debug:   gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
debug:   gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
debug:   gyp ERR! System Windows_NT 10.0.14393
debug:   gyp ERR! command "C:\\home\\meteor-azure\\nvm\\v14.18.1\\node.exe" "C:\\home\\meteor-azure\\nvm\\v14.18.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
debug:   gyp ERR! cwd C:\local\Temp\8d9b34023bcfd48\bundle\programs\server\node_modules\fibers
debug:   gyp ERR! node -v v14.18.1
debug:   gyp ERR! node-gyp -v v5.1.0
debug:   gyp ERR! not ok 
debug:   node-gyp exited with code: 1
debug:   Please make sure you are using a supported platform and node version. If you
debug:   would like to compile fibers on this machine please make sure you have setup your
debug:   build environment--
debug:   Windows + OS X instructions here: https://github.com/nodejs/node-gyp
debug:   Ubuntu users please run: `sudo apt-get install g++ build-essential`
debug:   RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
debug:   Alpine users please run: `sudo apk add python make g++`
debug:   'nodejs' is not recognized as an internal or external command,
debug:   operable program or batch file.
debug:   npm ERR! code ELIFECYCLE
debug:   npm ERR! errno 1
debug:   npm ERR! fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install: `node build.js || nodejs build.js`
debug:   npm ERR! Exit status 1
debug:   npm ERR! 
debug:   npm ERR! Failed at the fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install script.
debug:   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
debug:    
debug:   npm ERR! A complete log of this run can be found in:
debug:   npm ERR!     C:\local\AppData\npm-cache\_logs\2021-11-29T13_58_52_132Z-debug.log
debug:   meteor-azure: Could not install NPM dependencies
debug:   npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future\r\nnpm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future\r\ngyp ERR! build error \r\ngyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1\r\ngyp ERR! stack     at ChildProcess.onExit (C:\home\meteor-azure\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)\r\ngyp ERR! stack     at ChildProcess.emit (events.js:400:28)\r\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)\r\ngyp ERR! System Windows_NT 10.0.14393\r\ngyp ERR! command "C:\\home\\meteor-azure\\nvm\\v14.18.1\\node.exe" "C:\\home\\meteor-azure\\nvm\\v14.18.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"\r\ngyp ERR! cwd C:\local\Temp\8d9b34023bcfd48\bundle\programs\server\node_modules\fibers\r\ngyp ERR! node -v v14.18.1\r\ngyp ERR! node-gyp -v v5.1.0\r\ngyp ERR! not ok \r\nnode-gyp exited with code: 1\r\nPlease make sure you are using a supported platform and node version. If you\r\nwould like to compile fibers on this machine please make sure you have setup your\r\nbuild environment--\r\nWindows + OS X instructions here: https://github.com/nodejs/node-gyp\r\nUbuntu users please run: `sudo apt-get install g++ build-essential`\r\nRHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` \r\nAlpine users please run: `sudo apk add python make g++`\r\n'nodejs' is not recognized as an internal or external command,\r\noperable program or batch file.\r\nnpm ERR! code ELIFECYCLE\r\nnpm ERR! errno 1\r\nnpm ERR! fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install: `node build.js || nodejs build.js`\r\nnpm ERR! Exit status 1\r\nnpm ERR! \r\nnpm ERR! Failed at the fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install script.\r\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR!     C:\local\AppData\npm-cache\_logs\2021-11-29T13_58_52_132Z-debug.log\r\nmeteor-azure: Could not install NPM dependencies\r\nC:\Program Files (x86)\SiteExtensions\Kudu\95.30831.5373\bin\Scripts\starter.cmd bash script.sh
warn:   Failed to complete server initialisation
```

**Comment by ramijarrar** [comment]
I've updated the node-pre-gyp version in the [init script](https://github.com/fractal-code/meteor-azure-server-init) which should hopefully fix this issue (the current version does not support Node v14 which is used by Meteor 2.3+).

To test it out, edit your Meteor Azure settings to add a field `customServerInitRepo` with the value `https://github.com/fractal-code/meteor-azure-server-init.git#dev` then redeploy:

```js
{
  "meteor-azure": {
    "customServerInitRepo": "https://github.com/fractal-code/meteor-azure-server-init.git#dev",
    "siteName": "app name",
    // ... other settings
  }

  // ... keys for Meteor.settings
}
```

**Comment by 55** [comment]
@ramijarrar 

added suggested line:

![image](https://user-images.githubusercontent.com/7489044/143893098-822ba332-9a0a-42d4-9eac-ad7403d006c3.png)


and getting this when deploying

```
error:   Cannot read property 'details_url' of undefined
warn:   Could not retrieve deployment log
```

**Comment by ramijarrar** [comment]
Sorry, try this URL instead: https://github.com/ramijarrar/meteor-azure-server-init.git

**Comment by 55** [comment]
@ramijarrar trying to deploy to a newly created one:

```
Command: bash script.sh
debug:   meteor-azure: Installing NVM
debug:     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
debug:                                    Dload  Upload   Total   Spent    Left  Speed
debug:    
debug:     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
debug:     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
debug:   100   654  100   654    0     0   1211      0 --:--:-- --:--:-- --:--:--  1220
debug:    
debug:   100 2354k  100 2354k    0     0  2117k      0  0:00:01  0:00:01 --:--:-- 2117k
debug:   Archive:  nvm-noinstall.zip
debug:     inflating: nvm/LICENSE             
debug:     inflating: nvm/elevate.cmd         
debug:     inflating: nvm/elevate.vbs         
debug:     inflating: nvm/install.cmd         
debug:     inflating: nvm/nvm.exe             
debug:   meteor-azure: Now using NVM v1.1.7
debug:   meteor-azure: Setting Node to v14.18.1 64-bit
debug:   Downloading node.js version 14.18.1 (64-bit)... 
debug:   Complete
debug:   Creating D:\home\meteor-azure\nvm\temp
debug:    
debug:   Downloading npm version 6.14.15... Complete
debug:   Installing npm v6.14.15...
debug:    
debug:   Installation complete. If you want to use this version, type
debug:    
debug:   nvm use 14.18.1
debug:   meteor-azure: Now using Node v14.18.1 (64-bit)
debug:   meteor-azure: Now using NPM v6.14.15
debug:   meteor-azure: Installing rimraf tool
debug:   C:\home\meteor-azure\nvm\v14.18.1\rimraf -> C:\home\meteor-azure\nvm\v14.18.1\node_modules\rimraf\bin.js
debug:   + rimraf@3.0.2
debug:   added 12 packages from 4 contributors in 3.35s
debug:   meteor-azure: Installing global node-pre-gyp
debug:   C:\home\meteor-azure\nvm\v14.18.1\node-pre-gyp -> C:\home\meteor-azure\nvm\v14.18.1\node_modules\@mapbox\node-pre-gyp\bin\node-pre-gyp
debug:   + @mapbox/node-pre-gyp@1.0.7
debug:   added 55 packages from 22 contributors in 11.138s
debug:   meteor-azure: Unpacking bundle
debug:   meteor-azure: Using default web config
debug:   meteor-azure: Setting Node runtime
debug:   meteor-azure: Enabling IISNode logging
debug:   meteor-azure: Installing NPM dependencies
debug:   /tmp/8d9b356fe5d1ef1/bundle/programs/server /tmp/8d9b356fe5d1ef1
debug:   npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
debug:    
debug:   > fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install C:\local\Temp\8d9b356fe5d1ef1\bundle\programs\server\node_modules\fibers
debug:   > node build.js || nodejs build.js
debug:    
debug:    
debug:   C:\local\Temp\8d9b356fe5d1ef1\bundle\programs\server\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\home\meteor-azure\nvm\v14.18.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\home\meteor-azure\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release ) 
debug:   Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
debug:   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.props(28,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Redirect.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [C:\local\Temp\8d9b356fe5d1ef1\bundle\programs\server\node_modules\fibers\build\fibers.vcxproj]
debug:   gyp ERR! build error 
debug:   gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
debug:   gyp ERR! stack     at ChildProcess.onExit (C:\home\meteor-azure\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
debug:   gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
debug:   gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
debug:   gyp ERR! System Windows_NT 10.0.14393
debug:   gyp ERR! command "C:\\home\\meteor-azure\\nvm\\v14.18.1\\node.exe" "C:\\home\\meteor-azure\\nvm\\v14.18.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
debug:   gyp ERR! cwd C:\local\Temp\8d9b356fe5d1ef1\bundle\programs\server\node_modules\fibers
debug:   gyp ERR! node -v v14.18.1
debug:   gyp ERR! node-gyp -v v5.1.0
debug:   gyp ERR! not ok 
debug:   node-gyp exited with code: 1
debug:   Please make sure you are using a supported platform and node version. If you
debug:   would like to compile fibers on this machine please make sure you have setup your
debug:   build environment--
debug:   Windows + OS X instructions here: https://github.com/nodejs/node-gyp
debug:   Ubuntu users please run: `sudo apt-get install g++ build-essential`
debug:   RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
debug:   Alpine users please run: `sudo apk add python make g++`
debug:   'nodejs' is not recognized as an internal or external command,
debug:   operable program or batch file.
debug:   npm ERR! code ELIFECYCLE
debug:   npm ERR! errno 1
debug:   npm ERR! fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install: `node build.js || nodejs build.js`
debug:   npm ERR! Exit status 1
debug:   npm ERR! 
debug:   npm ERR! Failed at the fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install script.
debug:   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
debug:    
debug:   npm ERR! A complete log of this run can be found in:
debug:   npm ERR!     C:\local\AppData\npm-cache\_logs\2021-11-29T16_46_10_741Z-debug.log
debug:   meteor-azure: Could not install NPM dependencies
debug:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\r\n                                 Dload  Upload   Total   Spent    Left  Speed\r\n\r\n  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r\n  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r\n100   654  100   654    0     0   1211      0 --:--:-- --:--:-- --:--:--  1220\r\n\r\n100 2354k  100 2354k    0     0  2117k      0  0:00:01  0:00:01 --:--:-- 2117k\r\nnpm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future\r\ngyp ERR! build error \r\ngyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1\r\ngyp ERR! stack     at ChildProcess.onExit (C:\home\meteor-azure\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)\r\ngyp ERR! stack     at ChildProcess.emit (events.js:400:28)\r\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)\r\ngyp ERR! System Windows_NT 10.0.14393\r\ngyp ERR! command "C:\\home\\meteor-azure\\nvm\\v14.18.1\\node.exe" "C:\\home\\meteor-azure\\nvm\\v14.18.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"\r\ngyp ERR! cwd C:\local\Temp\8d9b356fe5d1ef1\bundle\programs\server\node_modules\fibers\r\ngyp ERR! node -v v14.18.1\r\ngyp ERR! node-gyp -v v5.1.0\r\ngyp ERR! not ok \r\nnode-gyp exited with code: 1\r\nPlease make sure you are using a supported platform and node version. If you\r\nwould like to compile fibers on this machine please make sure you have setup your\r\nbuild environment--\r\nWindows + OS X instructions here: https://github.com/nodejs/node-gyp\r\nUbuntu users please run: `sudo apt-get install g++ build-essential`\r\nRHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` \r\nAlpine users please run: `sudo apk add python make g++`\r\n'nodejs' is not recognized as an internal or external command,\r\noperable program or batch file.\r\nnpm ERR! code ELIFECYCLE\r\nnpm ERR! errno 1\r\nnpm ERR! fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install: `node build.js || nodejs build.js`\r\nnpm ERR! Exit status 1\r\nnpm ERR! \r\nnpm ERR! Failed at the fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install script.\r\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR!     C:\local\AppData\npm-cache\_logs\2021-11-29T16_46_10_741Z-debug.log\r\nmeteor-azure: Could not install NPM dependencies\r\nC:\Program Files (x86)\SiteExtensions\Kudu\95.30831.5373\bin\Scripts\starter.cmd bash script.sh
warn:    Failed to complete server initialisation
```

**Comment by 55** [comment]
I was able to deploy my app with Meteor 2.2.4 but any higher version still doesn't work

**Comment by ramijarrar** [comment]
Can you confirm the Platform setting (under "App Service > Settings > Configuration > General Settings > Platform") is set to "64-bit"?

**Comment by 55** [comment]
![image](https://user-images.githubusercontent.com/7489044/144219494-2b6e03cd-f44e-4db6-8b8a-26dc9fade33c.png)
